### ISSUE TITLE
MapView

### ISSUE THREAD

**Issue by alext146** [adtrahan146/EndGameMaps#2]
### Map View
The main view of the app.
**TODO:  Fill out following more:**

- [x] Uses Leaflet.js ( https://leafletjs.com/ ) 

- [x] Uses OpenStreetMap data as tilemap ( https://www.openstreetmap.org/ )

LATER:
- [x] Makes GET request to backend for all pin data

- [x] Listen for user clicks for:
pin creation & getting pin info
